Improve code security
clowd/Clowd pull request #2
Opened 2022-06-07 16:20 UTC by GermanAizek

@caesay, @rstarkov review code pull request and feedback me.

2022-06-07 17:02 UTC, caesay requested changes
Hi! Thanks for submitting this change. Do you mind me asking if you use Clowd and how you found out about it? Please join our discord if you are interested to discuss any further potential changes!

There are some really good improvements in this PR, however there are also a few places that I am unsure and need clarification from you.

2022-06-07 17:02 UTC, caesay commented on src/Clowd.WinNative/outline-text/OutlineText.cpp
> +    if (pBmpMask) pBmpMask->UnlockBits(&bitmapDataMask);
if any of these 3 locals are null, this method will crash earlier - eg. memory violation on line 652, so we probably don't need to check this here

2022-06-08 10:26 UTC, GermanAizek commented on src/Clowd.WinNative/DxScreenCapture.cpp
> +System::String DxScreenCapture::SaveSession(System::String sessionDirectory, const System::String& createdUtc)
@caesay, Yep, for sure I did not notice, I will fix it now.

2022-06-16 03:30 UTC, caesay commented
Closing this as it requires much feedback and there has been no activity. Feel free to open a new PR when the comments have been addressed.

2022-06-16 03:30 UTC, closed without merging